
const Routes = {
    SIGN_UP_SUCCESS: '/sign-up/success',
    SIGN_UP: '/sign-up',
    SIGN_IN: '/sign-in',
    FAQ: '/faq',
    FORGOT_PASS: '/forgot-password',
    HOME: '/',
    NOTIFICATIONS: '/notifications',
    MESSAGES: '/message-center',
    MY_PROFILE: '/profile',
    PROFILE_ID: '/profile:id',
    PUBLICITY: '/promote',
    PRODUITS_DASH: '/products/dashboard',
    PRODUITS_ADD: '/products/add',
    PRODUITS_EDIT: '/products/edit',
    PACKAGES: '/packages/list',
    PACKAGES_ADD: '/packages/add',
    PACKAGES_EDIT: '/packages/edit',
    COMMENTS: '/packages/comments',
    CUSTOMERS_DASH: '/customers/list',
    CUSTOMERS_ADD: '/customers/add',
    CUSTOMERS_EDIT: '/customers/edit',
    RESERVATION_DASH: '/reservations/list',
    RESERVATION_ADD: '/reservations/add',
    RESERVATION_EDIT: '/reservations/edit',
    AGENDA_DASH: '/reservations/agenda',
    INCOME_ADD: '/income/add',
    INCOME_EDIT: '/income/edit',
    INCOME_DASH: '/incomes/list',
    SETTINGS: '/settings',
};

export default Routes;