import AffiliateCenter from "./AffiliateCenter";
import CreateLink from "./AffiliateCenter/CreateLink";
import PerformanceByDay from "./AffiliateCenter/PerformanceByDay";
import Snapshot from "./AffiliateCenter/Snapshot";
import Chart from "./AffiliateCenter/Snapshot/Chart";
import Item from "./AffiliateCenter/Snapshot/Item";
import Table from "./AffiliateCenter/Table";
import Item from "./AffiliateCenter/Table/Item";
import Comments from "./Comments"
import Panel from "./Comments/Panel";
import Table from "./Comments/Table";
import Row from "./Comments/Table/Row";
import Control from "./Comments/Table/Row/Control";
import CustomerList from "./CustomerList"
import Details from "./CustomerList/Details";
import Head from "./CustomerList/Details/Head";
import PurchaseHistory from "./CustomerList/Details/PurchaseHistory";
import Panel from "./CustomerList/Panel";
import Settings from "./CustomerList/Settings";
import Table from "./CustomerList/Table";
import Row from "./CustomerList/Table/Row";
import Customers from "./Customers"
import ActiveCustomers from "./Customers/ActiveCustomers";
import Message from "./Customers/Message";
import NewCustomer from "./Customers/NewCustomer";
import Overview from "./Customers/Overview";
import Chart from "./Customers/Overview/Chart";
import ShareProducts from "./Customers/ShareProducts";
import TopCountry from "./Customers/TopCountry";
import TopDevice from './Customers/TopDevice';
import TrafficChannel from "./Customers/TrafficChannel";
import Drafts from "./Drafts"
import Panel from "./Drafts/Panel";
import Earning from "./Earning"
import Overview from "./Earning/Overview";
import ProductSales from "./Earning/ProductSales";
import Table from "./Earning/Table";
import TopCountries from "./Earning/TopCountries";
import ExploreCreators from "./ExploreCreators"
import Creator from "./ExploreCreators/Creator";
import Home from "./Home"
import Comments from "./Home/Comments";
import MoreCustomers from "./Home/MoreCustomers";
import Overview from "./Home/Overview";
import Chart from "./Home/Overview/Chart";
import Item from "./Home/Overview/Item";
import ProductViews from "./Home/ProductViews";
import ProTips from "./Home/ProTips";
import MessageCenter from "./MessageCenter"
import Messages from "./MessageCenter/Messages";
import Message from "./MessageCenter/Messages/Message";
import Panel from "./MessageCenter/Messages/Panel";
import Send from "./MessageCenter/Messages/Send";
import Users from "./MessageCenter/Users";
import Item from "./MessageCenter/Users/Item";
import NewProduct from "./NewProduct"
import CategoryAndAttibutes from "./NewProduct/CategoryAndAttibutes";
import Discussion from "./NewProduct/Discussion";
import ImagesAndCTA from "./NewProduct/ImagesAndCTA";
import NameAndDescription from "./NewProduct/NameAndDescription";
import Panel from "./NewProduct/Panel";
import Preview from "./NewProduct/Preview";
import Price from "./NewProduct/Price";
import ProductFiles from "./NewProduct/ProductFiles";
import Notification from "./Notification"
import Filters from "./Notification/Filters";
import List from "./Notification/List";
import Item from "./Notification/List/Item";
import Control from "./Notification/List/Item/Control";
import PageList from "./PageList"
import ProductsDashboard from "./ProductsDashboard"
import Overview from "./ProductsDashboard/Overview";
import Chart from "./ProductsDashboard/Overview/Chart";
import ProductActivity from "./ProductsDashboard/ProductActivity";
import Item from "./ProductsDashboard/ProductActivity/Item";
import Products from "./ProductsDashboard/Products";
import Control from "./ProductsDashboard/Products/Control";
import Market from "./ProductsDashboard/Products/Market";
import Row from "./ProductsDashboard/Products/Market/Row";
import Table from "./ProductsDashboard/Products/Table";
import Row from "./ProductsDashboard/Products/Table/Row";
import ProductViews from "./ProductsDashboard/ProductViews";
import Promote from "./Promote"
import Overview from "./Promote/Overview";
import RecentPost from "./Promote/RecentPost";
import NewPost from "./Promote/RecentPost/NewPost";
import Row from "./Promote/RecentPost/Row";
import Cell from "./Promote/RecentPost/Row/Cell";
import Refunds from "./Refunds"
import Row from "./Refunds/Row";
import Details from "./Refunds/Row/Details";
import Parameter from "./Refunds/Row/Details/Parameter";
import Product from "./Refunds/Row/Details/Product";
import Released from "./Released"
import Market from "./Released/Market";
import Row from "./Released/Market/Row";
import Panel from "./Released/Panel";
import Scheduled from "./Scheduled"
import Panel from "./Scheduled/Panel";
import Settings from "./Settings"
import Item from "./Settings/Item";
import Login from "./Settings/Login";
import Notifications from "./Settings/Notifications";
import Payment from "./Settings/Payment";
import ProfileInformation from "./Settings/ProfileInformation";
import SignIn from "./SignIn"
import SignUp from "./SignUp"
import Code from "./SignUp/Code";
import Entry from "./SignUp/Entry";
import Statements from "./Statements"
import Overview from "./Statements/Overview";
import Transactions from "./Statements/Transactions";